Repository wecode-bootcamp-korea/33-2nd-BranchTime-backend, pull requests merged in 2022-06, with the labels that each got.

#1 [BranchTime팀] django 초기세팅완료
  .gitignore
  branchtime/__init__.py
  branchtime/asgi.py
  branchtime/settings.py
  branchtime/urls.py
  branchtime/wsgi.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  manage.py
  my_settings.py
  requirements-dev.txt
  requirements-m1-dev.txt
  requirements.txt
Labels: 멘토 리뷰 요청

#2 [BranchTime팀] django 초기세팅 수정
  .gitignore
  my_settings.py
Labels: 완료

#3 [BranchTime팀] models.py 작성
  authors/__init__.py
  authors/admin.py
  authors/apps.py
  authors/migrations/0001_initial.py
  authors/migrations/__init__.py
  authors/models.py
  authors/tests.py
  authors/urls.py
  authors/views.py
  branchtime/settings.py
  branchtime/urls.py
  contents/__init__.py
  contents/admin.py
  contents/apps.py
  contents/migrations/0001_initial.py
  contents/migrations/__init__.py
  contents/models.py
  contents/tests.py
  contents/urls.py
  contents/views.py
  core/models.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: 멘토 리뷰 요청

#5 [BranchTime팀] models.py 일부수정
  users/migrations/0002_rename_social_acccunt_id_socialaccount_social_account_id_and_more.py
  users/models.py
Labels: 멘토 리뷰 요청

#6 [FIX] 모델링 변경
  contents/migrations/0002_remove_subcategory_post_post_subcategory.py
  contents/migrations/0003_alter_post_subcategory.py
  contents/migrations/0004_remove_post_thumbnail_post_sub_title_and_more.py
  contents/migrations/0005_alter_post_sub_title_alter_post_thumbnail_image_and_more.py
  contents/migrations/0006_alter_post_work.py
  contents/models.py
  users/migrations/0003_rename_uesr_socialaccount_user.py
  users/models.py
Labels: 멘토 리뷰 요청

#7 [BranchTime팀] KakaoLoginView 구현
  authors/migrations/0001_initial.py
  branchtime/settings.py
  contents/migrations/0001_initial.py
  contents/migrations/0002_remove_subcategory_post_post_subcategory.py
  contents/migrations/0003_alter_post_subcategory.py
  contents/migrations/0004_remove_post_thumbnail_post_sub_title_and_more.py
  contents/migrations/0005_alter_post_sub_title_alter_post_thumbnail_image_and_more.py
  contents/migrations/0006_alter_post_work.py
  users/migrations/0001_initial.py
  users/migrations/0002_rename_social_acccunt_id_socialaccount_social_account_id_and_more.py
  users/migrations/0003_rename_uesr_socialaccount_user.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: 멘토 리뷰 요청

#9 [BranchTime팀] models.py 일부수정
  authors/migrations/0002_rename_subscription_interestedauthor_and_more.py
  authors/models.py
  users/migrations/0002_subscription_user_subscription_and_more.py
  users/models.py
Labels: 멘토 리뷰 요청

#14 [FEAT] 댓글 입력 기능 추가
  contents/urls.py
  contents/views.py
  core/utils.py
  core/views.py
Labels: 도움 요청

#10 [BranchTime팀] UserDetailView 구현
  core/utils.py
  users/migrations/0001_initial.py
  users/migrations/0002_subscription_user_subscription_and_more.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Conflict 해결 요청, 수정 요청

#11 [FEAT] 글쓰기 기능 추가
  contents/urls.py
  contents/views.py
  core/utils.py
Labels: 멘토 리뷰 요청

#8 [FEAT] 글쓰기 내 이미지 업로드 기능 추가
  contents/tests.py
  contents/urls.py
  contents/views.py
  credentials.json
  token.json
Labels: 멘토 리뷰 요청

#16 [FEAT] 글 세부사항 보기 기능
  contents/urls.py
  contents/views.py
Labels: 멘토 리뷰 요청

#17 [FEAT] 댓글삭제기능
  contents/urls.py
  contents/views.py
Labels: 멘토 리뷰 요청

#18 [FEAT] 댓글수정 기능
  contents/urls.py
  contents/views.py
  core/views.py
Labels: 멘토 리뷰 요청

#19 [FEAT] 카테고리 항목 추출기능
  contents/views.py
Labels: 멘토 리뷰 요청

#21 [FIX] 모델링수정
  authors/migrations/0003_author_subcategory.py
  authors/migrations/0004_alter_author_subcategory.py
  authors/models.py
  core/views.py
  users/migrations/0003_alter_user_subscription.py
Labels: 멘토 리뷰 요청

#23 [FIX] 통신 오류 해결
  contents/views.py
  core/views.py
Labels: 멘토 리뷰 요청

#22 [FEAT] 작가 리스트 추출 기능
  authors/urls.py
  authors/views.py
Labels: 멘토 리뷰 요청

#27 [FIX] json 파일 삭제
  token.json
Labels: 멘토 리뷰 요청

#24 [BranchTime팀] PostListView 구현
  contents/tests.py
  contents/urls.py
  contents/views.py
Labels: 멘토 리뷰 요청

#29 [FIX] jsonfile삭제
  credentials.json
  token.json
Labels: 멘토 리뷰 요청
